/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;

/**
 *
 * @author darla
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    String nomeCliente, nomeMerc, cpf , codigo, descricao, dataCompra, dataValidade;
    float valor;
    ArrayList <Mercadoria> listaMerc;
    Cliente cliente;
    public Tela() {
        initComponents();
        listaMerc = new ArrayList();
        cliente = new Cliente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_titulo = new javax.swing.JLabel();
        jlb_mercadoria = new javax.swing.JLabel();
        jlb_cliente = new javax.swing.JLabel();
        jlb_codigo = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jlb_nomeMerc = new javax.swing.JLabel();
        jtf_nomeMerc = new javax.swing.JTextField();
        jlb_descricao = new javax.swing.JLabel();
        jtf_descricao = new javax.swing.JTextField();
        jlb_dataCompra = new javax.swing.JLabel();
        jtf_dataCompra = new javax.swing.JTextField();
        jlb_dataValidade = new javax.swing.JLabel();
        jtf_dataValidade = new javax.swing.JTextField();
        jlb_valor = new javax.swing.JLabel();
        jtf_valor = new javax.swing.JTextField();
        jlb_nomeCliente = new javax.swing.JLabel();
        jtf_nomeCliente = new javax.swing.JTextField();
        jtf_cpf = new javax.swing.JTextField();
        jlb_cpf = new javax.swing.JLabel();
        jbt_inserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_titulo.setFont(new java.awt.Font("BankGothic Md BT", 0, 12)); // NOI18N
        jlb_titulo.setText("Loja do Pedro Medina");

        jlb_mercadoria.setForeground(new java.awt.Color(0, 210, 0));
        jlb_mercadoria.setText("MERCADORIA");

        jlb_cliente.setForeground(new java.awt.Color(200, 0, 0));
        jlb_cliente.setText("CLIENTE");

        jlb_codigo.setText("CÓDIGO:");

        jtf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_codigoActionPerformed(evt);
            }
        });

        jlb_nomeMerc.setText("NOME:");

        jlb_descricao.setText("DESCRIÇÃO:");

        jlb_dataCompra.setText("DATA DA COMPRA:");

        jlb_dataValidade.setText("VALIDADE:");

        jlb_valor.setText("PREÇO:");

        jlb_nomeCliente.setText("NOME:");

        jlb_cpf.setText("CPF:");

        jbt_inserir.setText("Inserir");
        jbt_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlb_codigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_descricao)
                                    .addComponent(jlb_dataCompra)
                                    .addComponent(jlb_valor))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_dataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtf_dataCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                        .addComponent(jtf_descricao, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_dataValidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jlb_titulo))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jlb_nomeMerc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_nomeMerc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlb_cpf)
                                .addComponent(jlb_nomeCliente)
                                .addComponent(jlb_cliente))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlb_mercadoria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_mercadoria)
                    .addComponent(jlb_cliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_codigo)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_nomeCliente)
                    .addComponent(jtf_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nomeMerc)
                    .addComponent(jtf_nomeMerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cpf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_descricao)
                    .addComponent(jtf_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_dataCompra)
                    .addComponent(jtf_dataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_dataValidade)
                    .addComponent(jtf_dataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_valor)
                    .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_inserir))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_codigoActionPerformed

    private void limpartela()
    {
        jtf_codigo.setText("");
        jtf_nomeMerc.setText("");
        jtf_descricao.setText("");
        jtf_dataCompra.setText("");
        jtf_dataValidade.setText("");
        jtf_valor.setText("");
        jtf_cpf.setText("");
        jtf_nomeCliente.setText("");
    }
    private void jbt_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirActionPerformed
        //recebendo os dados da marcadoria
        nomeMerc = jtf_nomeMerc.getText();
        codigo = jtf_codigo.getText();
        descricao = jtf_descricao.getText();
        //IMPORTANTE!!
        // padrão de data dos Estados Unidos exemplo: 2002-Jan-31
        dataCompra = jtf_dataCompra.getText();
        dataValidade = jtf_dataValidade.getText();
        valor = Float.parseFloat(jtf_valor.getText());
        
        
        nomeCliente = jtf_nomeCliente.getText();
        cpf = jtf_cpf.getText();
        
        
        String enderecoServidor = "127.0.0.1";//Localhost.
        int portaServidor = 8000;          
        Socket socket;
        try{           
            socket = new Socket(enderecoServidor, portaServidor);           
            //ObjectInputStream recebe = new ObjectInputStream(socket.getInputStream());
            ObjectOutputStream envia = new ObjectOutputStream(socket.getOutputStream());
           
            
            envia.writeUTF(nomeCliente);
            envia.writeUTF(nomeMerc);
            envia.writeUTF(codigo);
            envia.writeUTF(cpf);
            envia.writeUTF(descricao);
            envia.writeFloat(valor);
            envia.writeUTF(dataCompra);
            envia.writeUTF(dataValidade);
            
            
            envia.flush();
            
            
        }catch (IOException e){
            System.out.println("Erro: " + e.getMessage());
        }
        
        limpartela();
    }//GEN-LAST:event_jbt_inserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt_inserir;
    private javax.swing.JLabel jlb_cliente;
    private javax.swing.JLabel jlb_codigo;
    private javax.swing.JLabel jlb_cpf;
    private javax.swing.JLabel jlb_dataCompra;
    private javax.swing.JLabel jlb_dataValidade;
    private javax.swing.JLabel jlb_descricao;
    private javax.swing.JLabel jlb_mercadoria;
    private javax.swing.JLabel jlb_nomeCliente;
    private javax.swing.JLabel jlb_nomeMerc;
    private javax.swing.JLabel jlb_titulo;
    private javax.swing.JLabel jlb_valor;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_cpf;
    private javax.swing.JTextField jtf_dataCompra;
    private javax.swing.JTextField jtf_dataValidade;
    private javax.swing.JTextField jtf_descricao;
    private javax.swing.JTextField jtf_nomeCliente;
    private javax.swing.JTextField jtf_nomeMerc;
    private javax.swing.JTextField jtf_valor;
    // End of variables declaration//GEN-END:variables
}
